### ISSUE TITLE
Issue with the path to js and css files in index

### ISSUE THREAD

**Issue by Dioude** [Zemke/starter-laravel-angular#11]
Hi,
i've managed to download and install your project on my local server, but when i run the public/ in my URL i got 3 errors : 
GET http://localhost/build/js/all-c0e8a190.js 
GET http://localhost/css/app.css 
GET http://localhost/build/css/all-932a5147.css

But my project is in www/angular/ and it looks like it's trying to reach root here. How can i fix this ? Maybe i missed something ?

**Comment by Zemke** [comment]
Hey Dioude,

I assume the errors are 404s. The three files you mentioned are only at this place once you run Gulp. Did you run Gulp? Did it throw any errors in the process?
