### ISSUE TITLE
Error while running gulp (elixir)

### ISSUE THREAD

**Issue by Dioude** [Zemke/starter-laravel-angular#12]
Hello,
i've read all the previous issues, and mine looks similare to the one resolved by #10 

But i've followed the steps and when i run "gulp" in my command menu, i got this errors : 
"'ErrorException' with message 'file_get_contents(C:\wamp\www\starter-laravel-angular\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\wamp\www\starter-laravel-angular\resources\views\layout.blade.php)' in C:\wamp\www\starter-laravel-angular\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:668"

And in the command it show : 
![gulp_elixir](https://cloud.githubusercontent.com/assets/2428990/7835410/073685e2-0479-11e5-8923-11e39edf4d4f.png)

i've tried all the solutions in every issue here but nothing work.

Don't know if it can help you but i got a warning when i enter "npm install" its "WARN package.json @ No repository field"

Thanks

**Comment by Zemke** [comment]
Hey Dioude,

did you run `composer install --prefer-dist`?

**Comment by Zemke** [comment]
Closing this as there's no further response. The error usually happens if you don't run `composer install --prefer-dist`.
