### ISSUE TITLE
Critical vulnerabilities in JSON Web Token libraries

### ISSUE THREAD

**Issue by nikeshbhagat** [Zemke/starter-laravel-angular#18]
Hi Zemke,

I think I mentioned this before, but really handy starter!

Anyway, I came across [this](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) article the other day and was wondering if your implementation addresses some of the concerns they mention. 

Just a friendly inquiry as I'm not strong with all the intricacies of JWT quite yet.

**Comment by Zemke** [comment]
Hi @nikeshbhagat,

thanks for the notice.

Zemke/starter-laravel-angular uses [tymondesigns/jwt-auth](https://github.com/tymondesigns/jwt-auth) to do the JWT job. The author of tymondesigns/jwt-auth wrote this about the issue: https://github.com/tymondesigns/jwt-auth/issues/139#issuecomment-109804759.

So, it should be fixed.
