### ISSUE TITLE
Auth question.

### ISSUE THREAD

**Issue by prigal** [Zemke/starter-laravel-angular#21]
Hi,

What is the purpose of these files : 
- Auth/AuthController.php
- Auth/PasswordController.php

They seems to not being used while signing up a user (or maybe I broke something !)

The UserController is fired with the store() method and with no validation.

**Comment by Zemke** [comment]
Hi,

indeed, they could be tossed as authentication is done on the Angular side with a Laravel endpoint `api/user/getByToken`.
