### ISSUE TITLE
Authentication for all pages?

### ISSUE THREAD

**Issue by uixdimi** [Zemke/starter-laravel-angular#22]
Anyone could give me tips on how to require authentication for all pages? Then if user logs in - to redirect to home page?

I've done something like this:

``` php
$routeProvider
      .when('/', {
        templateUrl: '/partials/index',
        controller: 'MainController',
        authenticate: true
      })
      .when('/:category/:action?/:id?', {
        templateUrl: function (params) {
          var allowedParams = ['category', 'action', 'id'];
          var paramVals = [];
          for (var key in params) {
            if (allowedParams.indexOf(key) !== -1) {
              paramVals.push(params[key]);
            }
          }
          return '/partials/' + paramVals.join('/');
        },
        authenticate: true
      })
      .otherwise({
        redirectTo: '/auth/login'
      });
```

But seems like something is not right.

Any tips?

**Comment by Zemke** [comment]
Users can be authentication with the API endpoint `api/user/getByToken`. The Angular service is [here](https://github.com/Zemke/starter-laravel-angular/blob/master/resources/assets/js/services/UserService.js#L13).

If you want to require authentication for anything, I would suggest to intercept any request and check authentication state of the user. An interceptor is already in use [here](https://github.com/Zemke/starter-laravel-angular/blob/master/resources/assets/js/appRoutes.js#L26).
The auth token is already set there. You could redirect the user for example if it's not set.
Keep in mind that you should also always have a server-side authentication check as client-side security can easily be bypassed.

If you have any more question, I'm glad to help.
