### ISSUE TITLE
installation error.

### ISSUE THREAD

**Issue by tapas4you** [Zemke/starter-laravel-angular#23]
Hi,
when i am going to install your application it gives error:
file_get_contents(E:\wamp\www\starter-laravel-angular\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: E:\wamp\www\starter-laravel-angular\resources\views\layout.blade.php)

node is installed
npm is installed but gulp is not found.
please guide me to make it.
Thanks

**Comment by Zemke** [comment]
If Gulp is not found, then I guess you haven't got it installed (globally). To install Gulp globally execute `npm install -g gulp`. Then try again.

`file_get_contents(E:\wamp\www\starter-laravel-angular\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: E:\wamp\www\starter-laravel-angular\resources\views\layout.blade.php)` is an error that occurs when `composer install --prefer-dist` wasn't run.

If problems persist, just comment here again, I'm glad to help.

**Comment by PaoloNardini** [comment]
Hello!
I made a fresh install and got the same error:

file_get_contents(C:\xampp\htdocs\starter-laravel-angular\public/build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\starter-laravel-angular\resources\views\layout.blade.php)

gulp installed and run succesfully
composer install --prefer-dist  run more than once without errors

What else?

**Comment by PaoloNardini** [comment]
I found the solution myself:

In gulpfile.js I added public/ path to files listed in version, resulting in:

...
 .version([
      'public/css/all.css',
      'public/js/all.js'
    ])
...

running gulp again it generate rev-manifest.json properly.
