### ISSUE TITLE
Something wrong with Elixir

### ISSUE THREAD

**Issue by husnulhamidiah** [Zemke/starter-laravel-angular#27]
I try perfectly and exactly as you write but I got an issue like this..

```
file_get_contents(C:\xampp\htdocs\lvmaster\public/build/rev-manifest.json): failed to open stream: No such file or directory
```

Can you give me a shot to solve this?

**Comment by appkr** [comment]
Not tested thought, try this:

``` php
.version([
      'public/build/css/all.css',
      'public/build/js/all.js'
    ]);
//.copy(...)
//.copy(...);
```

**Comment by husnulhamidiah** [comment]
Yeah it solved the error shown when I run gulp command.
But the main problem still there.
rev-manifest.json not found.

**Comment by Zemke** [comment]
I've come across `rev-manifest.json not found` a couple of times myself. Running `composer install --prefer-dist` has always fixed this for me.

**Comment by husnulhamidiah** [comment]
I've tried clean install and use `composer install --prefer-dist` but still `rev-manifest.json` not generated..
Any idea?

**Comment by Zemke** [comment]
Consider this issue comment. https://github.com/Zemke/starter-laravel-angular/issues/23#issuecomment-125245170

**Comment by shiruken1** [comment]
Ditto. Solved my issue by reinstalling npm, then installing gulp globally, running npm install laravel-elixir on the app folder, then modifying gulpfile.js as mentioned above, then finally running gulp.

Out of curiosity why not commit that change to the gulpfile, since it seems to be an issue?
