### ISSUE TITLE
Unix Socket in config causes issues with install

### ISSUE THREAD

**Issue by mattnelsonuk** [Zemke/starter-laravel-angular#30]
Great boilerplate! It's really helped me get to grips with AngularJS.

The default socket in starter-laravel-angular/config/database.php will throw people who are installing this without xampp. Can it be removed by default?

**Comment by hbickerton** [comment]
2nded, had to remove it to run migrations on linux.

**Comment by Zemke** [comment]
Thanks! Have fun with Laravel and AngularJS.
