### ISSUE TITLE
artisan app:name crashes my starter-laravel-angular

### ISSUE THREAD

**Issue by lampsbr** [Zemke/starter-laravel-angular#32]
Hi,

I got a fresh copy of starter-laravel-angular, made a few changes and everything was going fine, until I tried to change my namespace. Got this when tried to change it: 

bruno@brno ~/workspaceUTF8/starter-laravel-angular $ php artisan app:name csd
PHP Fatal error:  Cannot redeclare class csd\Exceptions\Handler in /home/bruno/workspaceUTF8/starter-laravel-angular/app/Exceptions/Handler.php on line 42
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Todo\Exceptions\Handler does not exist' in /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php:1286
Stack trace:
#0 /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php(1286): ReflectionClass->__construct('Todo\Exceptions...')
#1 /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php(1237): Illuminate\Container\Container->build('Todo\Exceptions...', Array)
#2 /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php(1775): Illuminate\Container\Container->make('Todo\Exceptions...', Array)
#3 /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php(1060): Illuminate\Foundation\Application->make('Todo\Exceptions...', Array)
#4 /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php(1284): Illuminate\Container\Container->Illuminate\Container{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /home/bru in /home/bruno/workspaceUTF8/starter-laravel-angular/bootstrap/cache/compiled.php on line 1286

The artisan command pretty much crashed after this. So I got another fresh copy of the code and tried it before making any change. Sadly the problem ocurred anyway. 

Does anyone knows how can I fix it?

Thanks in advance, sorry for my broken english and congrats for this nice piece of code. =D

**Comment by CrisOrrego** [comment]
Hi, I had the same problem, it seems to be fixed after i did: composer dump-autoload
