### ISSUE TITLE
file_get_contents(/app/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /app/resources/views/layout.blade.php)

### ISSUE THREAD

**Issue by jonaths** [Zemke/starter-laravel-angular#33]
Hi. I am trying to upload this starter to heroku, and I get this error:

file_get_contents(/app/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /app/resources/views/layout.blade.php)

The program works well offline on Homestead, but when I push the changes to Heroku this error appears. You can check it out at https://dry-lake-8666.herokuapp.com/. 

This is the gulpfile.js

var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function (mix) {
  mix
    .less(
      'app.less'
    )
    .styles([
      'style.css'
    ])
    .scripts([
      'libs/**/*.js',
      'app.js',
      'appRoutes.js',
      'controllers/**/_.js',
      'services/__/_.js',
      'directives/*_/_.js'
    ])
    .version([
      'public/css/all.css',
      'public/js/all.js'
    ])
    .copy(
    'public/js/all.js.map', 'public/build/js/all.js.map'
  )
    .copy(
    'public/css/all.css.map', 'public/build/css/all.css.map'
  );
});

And this are the contents of rev-manifest.json:

{
  "css/all.css": "css/all-dd351c50bd.css",
  "js/all.js": "js/all-ee8c46d8d5.js"
}

Do you know how can I fix it?

**Comment by jonaths** [comment]
Ok.. I know what was going on. I was not pushing the public/build directory where the json file was. I commented it from the .gitignore and now it works.

**Comment by jonaths** [comment]
Now I have another issue. My CSS files are not working on the heroku version but they do work within Homestead. Seems like the styles come from less files and there are no less files on Heroku. Do you have any idea please?

**Comment by Zemke** [comment]
Hey!

I have added a Heroku deployment manual to `README.md`. If you happen to have any problems with the manual, please report back.
