### ISSUE TITLE
Hi! Im getting some issues with Tymon JWT

### ISSUE THREAD

**Issue by jonaths** [Zemke/starter-laravel-angular#37]
When I try to login or register i get this error: 

ReflectionException in Container.php line 741:
Class Tymon\JWTAuth\Providers\Storage\Illuminate does not exist

I cloned the repo and added some migrations, seeds and models. I tried composer dump-autoload and verified the app config. Do you have some idea about what can I do? Thanks!

**Comment by Zemke** [comment]
Seems like JWTAuth dependency is missing for you.

Did you run `composer install --prefer-dist`?

**Comment by jonaths** [comment]
Yes... I realized I had some issue with that dependency. Since it was a new project I just reinstalled it all. I dont remember very well but I believe the reason was i ran some cache related command which created an entry inside bootstrap/cache. I would like to remember well what happened. Thanks anyway.

**Comment by Zemke** [comment]
Alright, good it works for you. Have fun!
