### ISSUE TITLE
Different templates

### ISSUE THREAD

**Issue by jonaths** [Zemke/starter-laravel-angular#38]
Hi Zemke. I want to add another layout for some views. Specifically I modified layout.blade.php to offer an admin like view with a sidebar and some other useful stuff. However this view makes no sense if the user is not logged in. As it is now the route auth/login shows the login fields inside the admin view. Id like to add a new almost blank view for some routes such as '/', '/auth/login and 'auth/signup', however I cant find out how to do this. In normal laravel blade stuff I usually did this with the @extends directive but I dont want to rely on laravel for the front end. Could you give me some guide? Thanks.

**Comment by Zemke** [comment]
Maybe [`$routeProvider`](https://docs.angularjs.org/api/ngRoute/provider/$routeProvider) is what you’re looking for.

**Comment by Zemke** [comment]
Closing due to no further response.
