### ISSUE TITLE
npm install doesn't work when using homestead

### ISSUE THREAD

**Issue by godbout** [Zemke/starter-laravel-angular#4]
Not your fault, seems like the homestead version of npm (coming with ubuntu) is too old and has some issues. Will post a fix here once I've found one.

**Comment by Zemke** [comment]
Thank you! I haven’t used Homestead, so I didn’t come across that. Looking forward to the fix. :wink:

**Comment by godbout** [comment]
Actually the fix is simple, just need to run

```
sudo npm -g install npm@next
```

to bump to the latest version of npm. Then running

```
sudo npm install
```

and it's all good :)

Thanks for the repo! It clarified some things I didn't quite understand before with JWTAuth.

**Comment by Zemke** [comment]
Okay, thanks for the response. I’m happy the repo could help you with that. :)
