### ISSUE TITLE
New angular dependencies

### ISSUE THREAD

**Issue by jonaths** [Zemke/starter-laravel-angular#40]
Hi Zemke. I am testing your code and I would like to add some dependencies using npm running the following command at the project root: 

npm install datatables.net

I can see npm downloading the files to a node_modules at the project root. However I see there is an angular_modules at resources/assets/js/libs/angular_modules. The gulpfile includes this folder with 'libs/*_/_.js'. My question is: within your app, which would be the proper way to use npm to install a library and use it inside a controller? Thanks.

**Comment by Zemke** [comment]
As it is right now, you'd manually add the dependencies. To keep it simple and focused on Laravel and AngularJS integration, I did not include anything like that.

There's a pull request #25 by @pierrerigal that introduces Bower integration. You could take advantage of that and do dependency management with Bower.
