### ISSUE TITLE
Upgrade to 5.3?

### ISSUE THREAD

**Issue by nemanjam** [Zemke/starter-laravel-angular#42]
Can you upgrade this to Laravel 5.3 please?

**Comment by Zemke** [comment]
If McDonald’s Wi-Fi was better, it would’ve already been there—it’s `git push`ing. 🍔

**Comment by Zemke** [comment]
Okay, I can’t solely blame McDonald’s Wi-Fi for it, because my Mac downloaded huge amount of data as it hadn’t been connected for a long time.

Anyways, Laravel 5.3 has landed along with Angular 1.5.8.  Have fun! 6ff99dc452135472412ed56c69f82d311fc12cc6
