### ISSUE TITLE
Inquiry on template system

### ISSUE THREAD

**Issue by ghost** [Zemke/starter-laravel-angular#49]
Many template contain `@extends('app')`

but in the file system I only can find `app.blade.php` but I can find `layout.blade.php` in
`/resources/views`

Is the app a reserved word to point to the layout.blade.php file?
Thanks.

**Comment by Zemke** [comment]
Those `*blade.php` files are clutter in this project. They could be removed. They came with Laravel or something. What’s used is `layout.blade.php` and the partials.
