### ISSUE TITLE
Problems with elixir after fresh install ?

### ISSUE THREAD

**Issue by Vvaltz** [Zemke/starter-laravel-angular#6]
Hey, I'm a big newbie, and I've been trying to find some bootstrap project that would help me start, and I figured this is could be perfect, yet I ran into some problems, if you would be kind enough to explain, that would be amazing:
1. Fresh install - do instructions, try running gulp, I get:

![Image of err1](http://i.imgur.com/O6q8n3c.jpg) 

Try adding these files manually: 
resources/assets/style.css works if I add it myself

These two I don't know how to do, they are mistakenly being looked for in assets directory, when they are just in js directory: 

File not found: resources/assets/js/app.js
File not found: resources/assets/js/appRoutes.js

Should be like:

resources/js/app.js
resources/js/appRoutes.js

If I try to add this myself:
File not found: public/js/all.js

It disappears after running gulp

Because of these gulp tasks not running I get an error when I try to serve the app :

![Image of err2](http://i.imgur.com/OcXqKGC.jpg) 

Or am I doing something wrong? I swear I tried instructions 3 times (also, "php -S localhost:8080 -t public/" is not working - for me at least only "php -S localhost:8080 -t public" (without the "/") works. Php artisan serve returns same error. I'm running windows 7 64bit

Any help?

**Comment by Zemke** [comment]
Hey Vvaltz,

thank you for trying out starter-laravel-angular.

I tend to think the problem is your operating system, Windows. I haven't ever tried using Windows for this, so I rode my bike to my girlfirend specifically for you, because she owns one of the species we use to call "Windows".
Well, I also didn't manage to set it up under Windows. I recommend you start using Ubuntu if you want to do these kinds of things.

**Comment by Vvaltz** [comment]
Wow, I'm sorry to have bothered you like that, thanks a lot for your response!

Yes, I think I will consider to try something like Ubuntu in a couple of weeks, cheers :)

**Comment by Zemke** [comment]
Hehe, to be honest, I was about to drive to her anyway. :stuck_out_tongue: 

If you run into problems under Ubuntu, I will be glad to give you a hand.

Have a nice day!

**Comment by fer-ri** [comment]
same with me, problem remains under Windows .. hehhe ..

**Comment by Zemke** [comment]
@Vvaltz and @ghprod, fix in #10 merged into master. Sorry, I didn't know Elixir changed assetDir. Thanks to @jaden!

**Comment by fer-ri** [comment]
:+1:

Thanks :dancer:
