### ISSUE TITLE
Trouble changing the namespace

### ISSUE THREAD

**Issue by nikeshbhagat** [Zemke/starter-laravel-angular#7]
Hello,

First, thank you for this excellent starter kit!

I'm trying to change the namespace after cloning the repo, running composer install, npm install, gulp, etc., but I keep getting a fatal error:  Class 'App\User' not found

I'm using homestead and I can get everything working beautifully, but as soon as I do "php artisan app:name App" - I get the Class no found error.

Any idea what's going on here? I see that you changed the namespace from tel to 'Todo' a couple months ago, how can I go about doing this?

Kind Regards,

Nikesh.

**Comment by nikeshbhagat** [comment]
I've "composer dump-autoload" and then "composer update" as well as making sure everything is consistent in Bootstrap\app and composer.json...

Stumped.

**Comment by nikeshbhagat** [comment]
Okay. Tired eyes. Simplest solution: change the namespace of User.php. _facepalm_ Very sorry for the inconvenience.

**Comment by Zemke** [comment]
Hehe, no problem.  Glad you’ve fixed the problem and happy you like starter-laravel-angular. Have fun!
