### ISSUE TITLE
Latest elixir expects css and js to be in resources/assets

### ISSUE THREAD

**Issue by jaden** [Zemke/starter-laravel-angular#9]
Elixir changed the default assetsDir and since package.json allows any version of larave-elixir, starter-laravel-angular is broken until you move css and js into resources/assets, or pin laravel-elixir to an older version.

**Comment by hojabbr** [comment]
Same problem

**Comment by Zemke** [comment]
Thanks for pointing that out. Can you say what it should be pinned to without investing too much time? Would very much appreciate a pull request.

**Comment by jaden** [comment]
I'm not sure of the version to pin to, I just went with moving the css and js folders over. I can send over a pull request for that if you want.

**Comment by jaden** [comment]
I just sent in a pull request with the folders moved.
